workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $CI_COMMIT_BRANCH =~ /^manticore-.*$/ && $CI_COMMIT_TITLE != $DOCS_AUTOCOMMIT_TITLE
    - if: $TEST
    - if: $WHAT

# to skip ci add [ci skip] or [skip ci] in commit message in any capitalization,
# or add param when pushing, as: git push -o ci.skip ...

variables:
  DOCS_AUTOCOMMIT_TITLE: 'Docs_examples_update'
  DOCS_EXAMPLES_FILEPATH: 'build/test/examples.txt'
  VERBOSE: 1

stages:
  - hooks

# ==================== Run secondary pipeline ======================

deploy_hook:
  stage: hooks
  variables:
    WHAT: $WHAT
    REPO_NAME: $REPO_NAME
  rules:
    - if: $CI_COMMIT_TITLE !~ /^noci .*$/i
      when: on_success
  trigger:
    include: dist/gitlab-release.yml
