stages:
  - mirroring
  - routines
  - build
  - publish

include: '/dist/gitlab-release.yml'

pages:
  stage: routines
  tags:
    - docker
  image: registry.gitlab.com/manticoresearch/dev/manticoredocs:latest
  script:
    - cd docs
    - make html
    - cd -
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

job_mirror:
  stage: mirroring
  tags:
    - dev-host
  only:
    - master
  script:
    - ~/gitsync.sh

simple_tests:
  stage: routines
  except:
    variables:
      - $WHAT
  tags:
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
  script:
    - ctest -VV -S misc/ctest/gltest.cmake
    - cd build && mkdir here1
    - cp -r Testing/2*/*.xml here1
  artifacts:
    paths:
    - build/here1
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log
    expire_in: 12 hrs
    when: always
  retry: 1

release_tests:
  stage: routines
  except:
    variables:
      - $WHAT
  tags:
    - specdocker
  dependencies: []
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  variables:
    CTEST_BUILD_CONFIGURATION: "RelWithDebInfo"
  script:
    - ctest -VV -S misc/ctest/gltest.cmake
    - cd build && mkdir here2
    - cp -r Testing/2*/*.xml here2
  artifacts:
    paths:
    - build/here2
    - build/test/test_*/report.txt
    - build/test/error*.txt
    - build/test/searchd.log
    expire_in: 12 hrs
    when: always
  retry: 1

build_win:
  stage: routines
  except:
    variables:
      - $WHAT
  tags:
    - windows
    - build
  dependencies: []
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
    LIBS_BUNDLE: "x:/bundle"
    CTEST_CMAKE_GENERATOR: "Visual Studio 14"
  script:
    - 'net use x: \\\\VBOXSRV\\shared'
    - mkdir build && cd build
    - ctest -VV -S ../misc/ctest/justbuild.cmake -DCTEST_SOURCE_DIRECTORY=..
    - mkdir here3
    - cp -r Testing/2*/*.xml here3
  artifacts:
    paths:
      - build/here3
    expire_in: 12 hrs
    when: always
  retry: 1

build_mac:
  stage: routines
  except:
    variables:
      - $WHAT
  tags:
    - mac
    - build
  dependencies: []
  variables:
    CTEST_BUILD_CONFIGURATION: "Debug"
    LIBS_BUNDLE: "/work"
    CTEST_CMAKE_GENERATOR: "Unix Makefiles"
  script:
    - mkdir build && cd build
    - ctest -VV -S ../misc/ctest/justbuild.cmake -DCTEST_SOURCE_DIRECTORY=..
    - mkdir here4
    - cp -r Testing/2*/*.xml here4
  artifacts:
    paths:
      - build/here4
    expire_in: 12 hrs
    when: always
  retry: 1

push_results:
  stage: publish
  except:
    variables:
      - $WHAT
  tags:
    - specdocker
  image: registry.gitlab.com/manticoresearch/dev/ubertests:latest
  dependencies:
    - simple_tests
    - release_tests
    - build_win
    - build_mac
  variables:
    GIT_STRATEGY: fetch
  script:
    - ctest -S misc/ctest/upload.cmake
  when: always
  artifacts:
    reports:
      junit: build/junit_*.xml
  environment:
    name: ${CI_COMMIT_REF_NAME}
    url: http://$CDASH_URL/CDash/public/index.php?project=Manticoresearch&filtercount=1&field1=revision&compare1=63&value1=$CI_COMMIT_SHA
  retry: 1
  allow_failure: true
