name: CLT latest release installation tests
run-name: CLT latest release installation tests ${{ github.sha }}

on:
  schedule:
    - cron: '00 20 * * *'
  push:
    paths:
      - 'test/clt-tests/**'
    branches:
      - manticore-6.2.12
  pull_request:
    branches: [ master ]
    paths:
      - 'test/clt-tests/installation/**'

# cancels the previous workflow run when a new one appears in the same branch (e.g. master or a PR's branch)
concurrency:
  group: clt_nightly_${{ github.ref }}
  cancel-in-progress: true

jobs:
  commit_info:
    name: Commit info
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo "# Nightly tests of latest release" >> $GITHUB_STEP_SUMMARY
          echo "* Attempt: ${{ github.run_attempt }}" >> $GITHUB_STEP_SUMMARY

  clt_rhel_release_installation:
    name: Testing RHEL release packages installation
    strategy:
      fail-fast: false
      matrix:
        image: [ "centos:7", "almalinux:8", "almalinux:9", "oraclelinux:9", "amazonlinux:latest" ]
    runs-on: ubuntu-22.04
    steps:
      - uses: manticoresoftware/clt@0.1.13
        with:
          ref: manticore-6.2.12
          image: ${{ matrix.image }}
          test_prefix: test/clt-tests/installation/rhel-release-
  clt_deb_release_installation:
    name: Testing DEB release packages installation
    strategy:
      fail-fast: false
      matrix:
        image: [ "ubuntu:bionic", "ubuntu:focal", "ubuntu:jammy", "debian:buster", "debian:bullseye", "debian:bookworm" ]
    runs-on: ubuntu-22.04
    steps:
      - uses: manticoresoftware/clt@0.1.13
        with:
          ref: manticore-6.2.12
          image: ${{ matrix.image }}
          test_prefix: test/clt-tests/installation/deb-release-

  clt_rhel_dev_update:
    name: Testing RHEL dev packages update
    strategy:
      fail-fast: false
      matrix:
        image: [ "centos:7", "almalinux:8", "almalinux:9", "oraclelinux:9", "amazonlinux:latest" ]
    runs-on: ubuntu-22.04
    steps:
      - uses: manticoresoftware/clt@0.1.13
        with:
          image: ${{ matrix.image }}
          test_prefix: test/clt-tests/installation/rhel-dev-u

  clt_deb_dev_update:
    name: Testing DEB dev packages update
    strategy:
      fail-fast: false
      matrix:
        image: [ "ubuntu:bionic", "ubuntu:focal", "ubuntu:jammy", "debian:buster", "debian:bullseye", "debian:bookworm" ]
    runs-on: ubuntu-22.04
    steps:
      - uses: manticoresoftware/clt@0.1.13
        with:
          image: ${{ matrix.image }}
          test_prefix: test/clt-tests/installation/deb-dev-u

  clt_comparison_overhead_json_sql:
    name: CLT test on comparison overhead json and sql
    needs: build_test_kit_docker
    runs-on: ubuntu-22.04
    steps:
      - uses: manticoresoftware/clt@0.1.17
        with:
          artifact: manticore_test_kit.img
          image: test-kit:img
          test_prefix: test/clt-tests/comparison-overhead-json-sql/
