name: Deploy docs

on:
  push:
    paths:
      - 'manual/**'
    branches:
      - docs-deploy-test
  pull_request:
    paths:
      - 'manual/**'
    branches:
      - docs-deploy-test
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: deploy_docs_${{ github.ref }}
  cancel-in-progress: true


jobs:
  docs_deploy:
    uses: ./.github/workflows/deploy_docs_template.yml
