name: Deploy docs

on:
  workflow_call:


env:
  DOCS_AUTOCOMMIT_TITLE: Docs_examples_update
  
jobs:
  docs_deploy:
    if: github.event.head_commit.message != "$DOCS_AUTOCOMMIT_TITLE"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    #    timeout-minutes: 30
    container:
      image: manticoresearch/docs_autodeploy_test:latest
      env:
        CACHEB: "../cache"
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        RELEASE_FILENAME: latest_release_version
        COMMIT_DIR: manual
        DEPLOY_SOURCE: github
        DEPLOY_TARGET: k8s
        DOCS_ERRORS_DIR: build/docs/
        DOCS_AUTOCOMMIT_TITLE: "$DOCS_AUTOCOMMIT_TITLE"
        DOCS_EXAMPLES_FILEPATH: 'build/test/examples.txt'

        CI_PROJECT_TITLE: dev
        CI_PROJECT_PATH: manticoresoftware/manticoresearch
        CI_PROJECT_DIR: /__w/manticoresearch/manticoresearch
        CI_COMMIT_SHA: ${{ github.sha }}
        CI_COMMIT_BRANCH: ${{ github.ref_name }}
        CI_COMMIT_TITLE: ${{ github.event.head_commit.message }}
    steps:
      - name: Install git
        run: |
          add-apt-repository ppa:git-core/ppa
          apt update
          apt install -y git

      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          set-safe-directory: true
          fetch-depth: 0

      - name: Initialization
        # without adding the safe.directory the script fails to do git show ...
        run: git config --global --add safe.directory /__w/manticoresearch/manticoresearch

      - name: Deploy
        run: |
          echo "Autocommit title $DOCS_AUTOCOMMIT_TITLE"

      - name: Upload artifact
        uses: manticoresoftware/upload_artifact_with_retries@main
        with:
          name: Docs error artifact
          path: $DOCS_ERRORS_DIR

