name: Publish Template

on:
  workflow_call:
    inputs:
      distr:
        required: true
        type: string
      arch:
        required: true
        type: string
      type:
        required: true
        type: string
      delimiter:
        required: true
        type: string

jobs:
  test:
    name: ${{ inputs.distr }}_${{ inputs.arch }}
    runs-on: ubuntu-22.04
    env:
      DISTRO: ${{ inputs.DISTR }}
      ARCH: ${{ inputs.arch }}
      DIGIT_DELIMITER2: ${{ inputs.delimiter }}
      REMOTE_SERVER: root@repo.manticoresearch.com
      SSH_KEY: ${{ secrets.REPO_SSH_KEY }}
      SSH_KEY_LOCATION: "~/.ssh/repo.key"
      TYPE: ${{ inputs.type }}
      DELIMITER: ${{ inputs.delimiter }}
    defaults:
      run:
        shell: bash
    steps:
      # - uses: manticoresoftware/download_artifact_with_retries@main
      #   with:
      #     name: build_rhel${DISTRO}_RelWithDebInfo_${ARCH}
      #     path: .
      # Uncomment this shortcut for debug to save time by not preparing the packages in the pack_focal job
      - run: |
          wget http://dev2.manticoresearch.com/build_focal_RelWithDebInfo_x86_64.zip
          unzip build_focal_RelWithDebInfo_x86_64.zip
          tar -xvf artifact.tar
      - run: |
          echo "mkdir"
          mkdir -p ~/.ssh/
          echo "ls -la ~"
          ls -la ~
          echo "cd .ssh"
          cd ~/.ssh
          echo "> repo.key"
          echo "${SSH_KEY}" > repo.key
          echo "writing to ${SSH_KEY_LOCATION}"
          echo "${SSH_KEY}" > ${SSH_KEY_LOCATION}
          echo "ls -la ~/.ssh/"
          ls -la ~/.ssh/
          chmod 600 ${SSH_KEY_LOCATION}
          cat >>~/.ssh/config <<END
          Host repo
            HostName ${REMOTE_SERVER}
            User root
            IdentityFile ${SSH_KEY_LOCATION}
            StrictHostKeyChecking no
          END
          TEMP_DIR=$(ssh -vv ${REMOTE_SERVER} "TEMP_DIR=\$(mktemp -d); if [ -z \"\$TEMP_DIR\" ]; then echo 'Failed to create temporary directory' >&2; exit 1; else echo \$TEMP_DIR; fi")
          scp build/*.{rpm,deb,tar.gz,exe} ${REMOTE_SERVER}:${TEMP_DIR}/build
          ssh ${REMOTE_SERVER} <<EOF
          cd ${TEMP_DIR}
          curl -sSL https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_${TYPE} > script
          chmod +x script
          DIGIT_DELIMITER2="${DELIMITER}" ls -la build
          ls -la script
          rm -rf ${TEMP_DIR}
          find /tmp -type d -ctime +7 -name 'tmp.*' -exec rm -rf {} \;
          EOF
